server:
  port: 8010
spring:
  application:
    name: book-store-service
  cloud:
    nacos:
      discovery:
        cluster-name: Shanghai
        ephemeral: false
      server-addr: 127.0.0.1:18848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1 # 每次仅预取一条消息
        acknowledge-mode: auto # 自动确认消息
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2

management:
  server:
    port: 8011
  endpoints:
    web:
      base-path: /actuator