server:
  port: 8010
spring:
  application:
    name: book-store-service
  cloud:
    nacos:
      discovery:
        cluster-name: Shanghai
        ephemeral: false
      server-addr: 127.0.0.1:18848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1 # 每次仅预取一条消息
        acknowledge-mode: manual # 手动确认消息

management:
  server:
    port: 8011
  endpoints:
    web:
      base-path: /actuator