server:
  port: 8020
spring:
  application:
    name: unite-book-service
  cloud:
    nacos:
      discovery:
        cluster-name: Shanghai
        ephemeral: false
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
management:
  server:
    port: 8021
  endpoints:
    web:
      base-path: /actuator